### ISSUE TITLE
Strange error on Ubuntu 14.04

### ISSUE THREAD

**Issue by DRVTiny** [eikonomega/oracle_instant_client_for_ubuntu_64bit#4]
I tried to do: "./install_oracle_instantclient.py .." and got this:

Traceback (most recent call last):
  File "./install_oracle_instantclient.py", line 116, in <module>
    setup.oracle_setup(sys.argv[1])
  File "./install_oracle_instantclient.py", line 75, in oracle_setup
    u'instantclient([0-9.]+)', self.rpm_files['basic'])[0]
IndexError: list index out of range

Hmm... what does it mean and what can i do to fix the problem?

My setup:
Ubuntu 14.04
Python 2.7.6
python-rpm installed
alien installed

Thank you!

**Comment by eikonomega** [comment]
Hi @DRVTiny, did you download the rpm files from Oracle's website?
If so, what are the names and the directory you placed them in?

Can you give me the full command that you executed, including the parameter to where the rpms are located?

**Comment by eikonomega** [comment]
@DRVTiny Closing because I didn't ever hear back on this from requestor.

**Comment by kdougan** [comment]
(this is old, I know) I overcame this by just updating the regex on line [75](https://github.com/eikonomega/oracle_instant_client_for_ubuntu_64bit/blob/c237b46303a71e40d1066b478daa92f9b7d3874c/install_oracle_instantclient.py#L75) to just read: 

`            u'([0-9.]+)', self.rpm_files['basic'])[0]`

I can submit a pull request, if the project is still maintained. :P
