### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by jobdiogenes** [eikonomega/oracle_instant_client_for_ubuntu_64bit#6]
after call
./install_oracle_instantclient.py  oradrivers
Traceback (most recent call last):
  File "./install_oracle_instantclient.py", line 116, in <module>
    setup.oracle_setup(sys.argv[1])
  File "./install_oracle_instantclient.py", line 68, in oracle_setup
    directory_containing_rpms))[0]
IndexError: list index out of range

**Comment by bluehorseshoe1** [comment]
Same as above.

**Comment by bluehorseshoe1** [comment]
###############################################################
This program will install and configure the Oracle Instant
Client on your system.

You must run this program as root for it to work correctly.
You will be prompted for permission to install software.
Say yes if you want the program to work. :)

Press enter to continue.
###############################################################


Traceback (most recent call last):
  File "install_oracle_instantclient.py", line 116, in <module>
    setup.oracle_setup(sys.argv[1])
  File "install_oracle_instantclient.py", line 75, in oracle_setup
    u'instantclient-basic-([0-9.]+)', self.rpm_files['basic'])[0]
IndexError: list index out of rang

**Comment by bluehorseshoe1** [comment]
oracle-instantclient12.2-basic-12.2.0.1.0-1.x86_64.rpm
oracle-instantclient12.2-devel-12.2.0.1.0-1.x86_64.rpm
 oracle-instantclient12.2-sqlplus-12.2.0.1.0-1.x86_64.rpm

**Comment by eikonomega** [comment]
Hey @bluehorseshoe1 - this project is something that I no longer maintain and it is quite out of date from the current Oracle files. I'd suggest that you look for a different solution.
